ALTER TABLE carts
    DROP CONSTRAINT carts_discount_check,
    ADD CONSTRAINT carts_discount_check CHECK (discount IN ('NO_DISCOUNT', 'DISCOUNT_5_PERCENT', 'DISCOUNT_10_PERCENT', 'DISCOUNT_15_PERCENT'));

SELECT *
FROM carts
WHERE discount NOT IN ('NO_DISCOUNT', 'DISCOUNT_5_PERCENT', 'DISCOUNT_10_PERCENT', 'DISCOUNT_15_PERCENT');

UPDATE carts
SET discount = 'NO_DISCOUNT'
WHERE discount IS NULL;

ALTER TABLE carts
    ALTER COLUMN discount SET DEFAULT 'NO_DISCOUNT';